#!/usr/bin/env python
import daemon
import urllib

class PodcastRipper(object):
    def start_server():
        while True:
            new_episodes = check_for_new_episodes()
            if new_episodes:
                download_new_episodes()

            new_podcasts = check_for_new_podcasts()
            if new_podcasts:
                download_new_podcasts()
        pass

    def check_for_new_episodes():
        pass

    def download_new_episodes():
        pass
    
    def check_for_new_podcasts():
        pass
        
    def download_new_podcasts():
        pass

    def add_podcast_to_database():
        pass

if __name__ == "__main__":    
    print("True")
